import type { Idioma } from '../idioma';

/** Diccionario de claves internas (en español) a etiquetas visibles. */
type Diccionario = Record<string, string>;

/**
 * Nombres de columna que devuelven las herramientas, en minúsculas para
 * buscarlos sin importar cómo vengan escritos en la base.
 */
const columnasEn: Diccionario = {
  id: 'ID',
  rutcliente: 'Customer ID (RUT)',
  rut: 'RUT',
  nombres: 'First names',
  nombre: 'Name',
  apellidos: 'Last names',
  paterno: 'Paternal surname',
  materno: 'Maternal surname',
  razonsocial: 'Company name',
  email: 'Email',
  celular: 'Mobile',
  movil: 'Mobile',
  telefono: 'Phone',
  comuna: 'District',
  nombreregion: 'Region',
  region: 'Region',
  atenciones: 'Service visits',
  ultima_atencion: 'Last visit',
  vehiculos: 'Vehicles',
  fechacreacion: 'Created',
  fecha: 'Date',
  momento: 'Time',
  nombreconcesionario: 'Dealer',
  concesionario: 'Dealer',
  nombrelocal: 'Branch',
  local: 'Branch',
  sucursal: 'Branch',
  punto_venta: 'Point of sale',
  asesor: 'Advisor',
  dueno: 'Salesperson',
  tipodocumento: 'Document type',
  descripcion: 'Description',
  km: 'Mileage (km)',
  ot: 'Work order',
  patente: 'License plate',
  vin: 'VIN',
  modelo: 'Model',
  familia: 'Family',
  valor: 'Value',
  cupones: 'Coupons',
  clientes: 'Customers',
  filas: 'Rows',
  comentario: 'Comment',
  columna: 'Column',
  tipo: 'Type',
  aceptanulos: 'Nullable',
  esclave: 'Key',
  estado: 'Status',
  valoracion: 'Temperature',
  modelo_interes: 'Model of interest',
  version_interes: 'Version of interest',
  origen: 'Source',
  utm_origen: 'Digital source',
  convertido: 'Converted',
  no_gestionado: 'Not handled',
  dias_hasta_seguimiento: 'Days to follow-up',
  direccion: 'Direction',
  destino: 'Destination',
  segundos_hablando: 'Talk time (s)',
  costo: 'Cost',
  resumen: 'Summary',
  transcripcion: 'Transcript',
  anexo: 'Extension',
  entrantesatendidas: 'Inbound answered',
  entrantesperdidas: 'Inbound missed',
  salientesatendidas: 'Outbound answered',
  salientesperdidas: 'Outbound missed',
  totalatendidas: 'Total answered',
  totalperdidas: 'Total missed',
  minutoshablados: 'Minutes talked',
  porcentajeatencion: 'Answer rate',
};

const columnasZh: Diccionario = {
  id: 'ID',
  rutcliente: '客户编号 (RUT)',
  rut: 'RUT',
  nombres: '名',
  nombre: '名称',
  apellidos: '姓',
  paterno: '父姓',
  materno: '母姓',
  razonsocial: '公司名称',
  email: '邮箱',
  celular: '手机',
  movil: '手机',
  telefono: '电话',
  comuna: '区',
  nombreregion: '大区',
  region: '大区',
  atenciones: '服务次数',
  ultima_atencion: '最近服务',
  vehiculos: '车辆',
  fechacreacion: '创建日期',
  fecha: '日期',
  momento: '时间',
  nombreconcesionario: '经销商',
  concesionario: '经销商',
  nombrelocal: '门店',
  local: '门店',
  sucursal: '门店',
  punto_venta: '销售点',
  asesor: '顾问',
  dueno: '销售员',
  tipodocumento: '单据类型',
  descripcion: '描述',
  km: '里程 (km)',
  ot: '工单',
  patente: '车牌',
  vin: 'VIN',
  modelo: '车型',
  familia: '车系',
  valor: '值',
  cupones: '工单券',
  clientes: '客户',
  filas: '行数',
  comentario: '备注',
  columna: '列',
  tipo: '类型',
  aceptanulos: '可为空',
  esclave: '键',
  estado: '状态',
  valoracion: '热度',
  modelo_interes: '意向车型',
  version_interes: '意向版本',
  origen: '来源',
  utm_origen: '数字渠道',
  convertido: '已转化',
  no_gestionado: '未跟进',
  dias_hasta_seguimiento: '跟进天数',
  direccion: '方向',
  destino: '目标号码',
  segundos_hablando: '通话时长 (秒)',
  costo: '费用',
  resumen: '摘要',
  transcripcion: '转写',
  anexo: '分机',
  entrantesatendidas: '呼入已接',
  entrantesperdidas: '呼入未接',
  salientesatendidas: '呼出已接',
  salientesperdidas: '呼出未接',
  totalatendidas: '已接合计',
  totalperdidas: '未接合计',
  minutoshablados: '通话分钟',
  porcentajeatencion: '接通率',
};

const en = {
  titulos: {
    operacion: 'Operations',
    ranking: 'Ranking',
    evolucion: 'Trend',
    evolucionPor: (granularidad: string) => `Trend by ${granularidad}`,
    resultado: 'Result',
    encuestas: 'After-sales surveys',
    leads: 'Leads',
    telefonia: 'Telephony',
  },
  dimensiones: {
    concesionario: 'Dealers',
    local: 'Branches',
    asesor: 'Advisors',
    tipoDocumento: 'Document types',
    familia: 'Families',
    modelo: 'Models',
    region: 'Regions',
    comuna: 'Districts',
  } as Diccionario,
  herramientas: {
    valores_dimension: 'Values in the database',
    buscar_cliente: 'Customers',
    buscar_lead: 'Leads',
    buscar_llamadas: 'Calls',
    anexos_telefonia: 'Phone extensions',
    historial_vehiculo: 'Vehicle history',
    consulta_sql: 'Custom query',
    listar_tablas: 'Tables',
    describir_tabla: 'Table structure',
  } as Diccionario,
  granularidades: { dia: 'day', semana: 'week', mes: 'month' } as Diccionario,
  ejesEncuestas: {
    concesionario: 'Satisfaction by dealer',
    sucursal: 'Satisfaction by branch',
    mes: 'Satisfaction by month',
    total: 'Overall satisfaction',
  } as Diccionario,
  ejesLeads: {
    valoracion: 'Leads by temperature',
    concesionario: 'Leads by dealer',
    punto_venta: 'Leads by point of sale',
    modelo_interes: 'Leads by model of interest',
    estado: 'Leads by status',
    origen: 'Leads by source',
    utm_origen: 'Leads by digital source',
    dueno: 'Leads by salesperson',
    fecha: 'Leads by day',
    total: 'Leads',
  } as Diccionario,
  resumen: {
    cuponesEmitidos: 'Coupons issued',
    localesActivos: 'Active branches',
    asesores: 'Advisors',
    clientesDistintos: 'Unique customers',
    vehiculos: 'Vehicles',
    concesionarios: 'Dealers',
    kilometrajePromedio: 'Average mileage',
    unidadKm: 'km',
  },
  vacios: {
    registros: 'No records in this period.',
    filas: 'The query returned no rows.',
    respuestas: 'No responses in this period.',
    leads: 'No leads in this period.',
    llamadas: 'No calls in this period.',
  },
  serie: {
    maximo: (valor: string) => `max. ${valor}`,
    descripcion: (intervalos: number, maximo: string) => `Series of ${intervalos} intervals, maximum ${maximo} coupons`,
    barra: (intervalo: string, valor: string) => `${intervalo}: ${valor} coupons`,
  },
  encuestas: {
    mes: 'Month',
    nombre: 'Name',
    respuestas: 'Responses',
    nps: 'NPS',
    satisfaccion: 'Satisfaction',
    recomendacion: 'Recommendation',
    nota: 'Scores from 1 to 7. NPS: promoter 7, passive 6, detractor 5 or less.',
  },
  llamadas: {
    grupo: 'Group',
    llamadas: 'Calls',
    atendidas: 'Answered',
    atencion: 'Answer rate',
    minutos: 'Minutes',
  },
  temperaturas: {
    superCalientes: 'Super hot',
    calientes: 'Hot',
    tibios: 'Warm',
    frios: 'Cold',
  },
  /** Valores que llegan en español desde la base y tienen traducción fija. */
  valores: {
    'Super Caliente': 'Super hot',
    Caliente: 'Hot',
    Tibio: 'Warm',
    'Frío': 'Cold',
    Frio: 'Cold',
    'sin dato': 'no data',
    Total: 'Total',
  } as Diccionario,
  si: 'Yes',
  no: 'No',
  columnas: columnasEn,
  datosEnmascarados: 'Masked personal data:',
  graficos: {
    sinMovimientos: 'No activity in this period.',
    sinDatos: 'No data in this period.',
    sinLeads: 'No leads in this period.',
    pico: 'peak',
    descripcionSerie: (dias: number, maximo: string, dia: string) =>
      `Series of ${dias} days. Maximum ${maximo} on ${dia}.`,
    descripcionArco: (porcentaje: string, pie: string) => `${porcentaje}. ${pie}`,
  },
  periodos: {
    anio: (anio: string) => `Year ${anio}`,
  },
};

export const textosBloques: Record<Idioma, typeof en> = {
  en,
  zh: {
    titulos: {
      operacion: '运营概览',
      ranking: '排名',
      evolucion: '趋势',
      evolucionPor: (granularidad: string) => `按${granularidad}趋势`,
      resultado: '结果',
      encuestas: '售后调查',
      leads: '线索',
      telefonia: '电话',
    },
    dimensiones: {
      concesionario: '经销商',
      local: '门店',
      asesor: '顾问',
      tipoDocumento: '单据类型',
      familia: '车系',
      modelo: '车型',
      region: '大区',
      comuna: '区',
    },
    herramientas: {
      valores_dimension: '数据库中的取值',
      buscar_cliente: '客户',
      buscar_lead: '线索',
      buscar_llamadas: '通话',
      anexos_telefonia: '电话分机',
      historial_vehiculo: '车辆历史',
      consulta_sql: '自定义查询',
      listar_tablas: '数据表',
      describir_tabla: '表结构',
    },
    granularidades: { dia: '日', semana: '周', mes: '月' },
    ejesEncuestas: {
      concesionario: '各经销商满意度',
      sucursal: '各门店满意度',
      mes: '各月满意度',
      total: '总体满意度',
    },
    ejesLeads: {
      valoracion: '按热度划分的线索',
      concesionario: '按经销商划分的线索',
      punto_venta: '按销售点划分的线索',
      modelo_interes: '按意向车型划分的线索',
      estado: '按状态划分的线索',
      origen: '按来源划分的线索',
      utm_origen: '按数字渠道划分的线索',
      dueno: '按销售员划分的线索',
      fecha: '按日划分的线索',
      total: '线索',
    },
    resumen: {
      cuponesEmitidos: '已开工单券',
      localesActivos: '活跃门店',
      asesores: '顾问',
      clientesDistintos: '独立客户',
      vehiculos: '车辆',
      concesionarios: '经销商',
      kilometrajePromedio: '平均里程',
      unidadKm: '公里',
    },
    vacios: {
      registros: '该期间没有记录。',
      filas: '查询没有返回任何行。',
      respuestas: '该期间没有回复。',
      leads: '该期间没有线索。',
      llamadas: '该期间没有通话。',
    },
    serie: {
      maximo: (valor: string) => `最高 ${valor}`,
      descripcion: (intervalos: number, maximo: string) => `共 ${intervalos} 个区间，最高 ${maximo} 张工单券`,
      barra: (intervalo: string, valor: string) => `${intervalo}：${valor} 张工单券`,
    },
    encuestas: {
      mes: '月份',
      nombre: '名称',
      respuestas: '回复数',
      nps: 'NPS',
      satisfaccion: '满意度',
      recomendacion: '推荐度',
      nota: '评分为 1 到 7 分。NPS：7 分为推荐者，6 分为中立者，5 分及以下为贬损者。',
    },
    llamadas: {
      grupo: '分组',
      llamadas: '通话',
      atendidas: '已接',
      atencion: '接通率',
      minutos: '分钟',
    },
    temperaturas: {
      superCalientes: '超热',
      calientes: '热',
      tibios: '温',
      frios: '冷',
    },
    valores: {
      'Super Caliente': '超热',
      Caliente: '热',
      Tibio: '温',
      'Frío': '冷',
      Frio: '冷',
      'sin dato': '无数据',
      Total: '合计',
    },
    si: '是',
    no: '否',
    columnas: columnasZh,
    datosEnmascarados: '已脱敏的个人数据：',
    graficos: {
      sinMovimientos: '该期间没有活动。',
      sinDatos: '该期间没有数据。',
      sinLeads: '该期间没有线索。',
      pico: '峰值',
      descripcionSerie: (dias: number, maximo: string, dia: string) => `共 ${dias} 天。${dia} 达到最高 ${maximo}。`,
      descripcionArco: (porcentaje: string, pie: string) => `${porcentaje}。${pie}`,
    },
    periodos: {
      anio: (anio: string) => `${anio}年`,
    },
  },
};
