import type { Idioma } from '../idioma';

const en = {
  sugerencias: [
    'Which point of sale gets the most leads, and at what temperature?',
    'How many hot leads are still open, and where do they come from?',
    'How is call volume trending by extension?',
    'Which branch issued the most service coupons last month?',
  ],
  nombreHerramienta: {
    resumen_operacion: 'operations summary',
    ranking: 'ranking',
    serie_temporal: 'trend over time',
    valores_dimension: 'dimension values',
    buscar_cliente: 'customer lookup',
    historial_vehiculo: 'vehicle history',
    consulta_sql: 'custom query',
    esquema_cupones: 'coupon table schema',
    listar_tablas: 'table list',
    describir_tabla: 'table structure',
    encuestas_posventa: 'after-sales surveys',
    leads: 'leads',
    buscar_lead: 'lead lookup',
    llamadas: 'calls',
    buscar_llamadas: 'call lookup',
    anexos_telefonia: 'phone extensions',
    esquema_gestion: 'management data schema',
  } as Record<string, string>,
  estadoConsultando: 'QUERYING',
  estadoListo: 'READY',
  bajada: 'WiWO Me · Executive intelligence',
  tituloBase: (base: string, privacidad: string) => `Database ${base}, privacy ${privacidad}`,
  registroTecnico: 'Technical log',
  vaciarConversacion: 'Clear the conversation',
  confirmarVaciado: 'Clear?',
  etiquetaOrbeApertura: 'WiWO Me Thinking Orb',
  aperturaTitulo: 'Ask the operation.',
  aperturaTexto:
    '87,441 service coupons since March 2025, with their dealer, branch, advisor and vehicle. Ask in plain language; the Thinking Orb queries the database and gives you the figure with its period.',
  consultandoBase: 'Querying the database:',
  pensando: 'Thinking',
  consultasALaBase: (cantidad: number) =>
    cantidad === 1 ? '1 database query' : `${cantidad} database queries`,
  placeholder: 'Ask the Thinking Orb…',
  etiquetaEntrada: 'Type your question',
  detenerConsulta: 'Stop the query',
  enviarPregunta: 'Send the question',
  aviso: 'The Thinking Orb only reads the database. Personal data is masked except in specific lookups.',
  servidorRespondio: (estado: number) => `The server responded ${estado}.`,
  consultaFallida: 'The query could not be completed.',
  orbe: {
    reposo: 'Thinking Orb idle',
    escuchando: 'Thinking Orb listening',
    pensando: 'Thinking Orb thinking',
    generando: 'Thinking Orb answering',
    error: 'Thinking Orb has a problem',
  },
  diagnostico: {
    tipo: { ronda: 'model', herramienta: 'database', error: 'error', turno: 'turn' },
    titulo: 'Technical log',
    eventos: (cantidad: number) => `${cantidad} events`,
    leyendo: 'Reading…',
    recargar: 'Reload',
    vaciar: 'Clear',
    cerrar: 'Close',
    errorLectura: 'Could not read the server log.',
    vacio: 'No events yet. Ask a question and check again.',
  },
};

export const textosChat: Record<Idioma, typeof en> = {
  en,
  zh: {
    sugerencias: [
      '哪个销售网点获得的线索最多？线索温度如何？',
      '还有多少热线索尚未成交？它们来自哪些渠道？',
      '各分机的通话量走势如何？',
      '上个月哪个网点开出的服务券最多？',
    ],
    nombreHerramienta: {
      resumen_operacion: '运营概览',
      ranking: '排名',
      serie_temporal: '时间趋势',
      valores_dimension: '维度取值',
      buscar_cliente: '客户查询',
      historial_vehiculo: '车辆历史',
      consulta_sql: '自定义查询',
      esquema_cupones: '服务券表结构',
      listar_tablas: '数据表列表',
      describir_tabla: '数据表结构',
      encuestas_posventa: '售后调查',
      leads: '销售线索',
      buscar_lead: '线索查询',
      llamadas: '通话',
      buscar_llamadas: '通话查询',
      anexos_telefonia: '电话分机',
      esquema_gestion: '管理数据结构',
    },
    estadoConsultando: '查询中',
    estadoListo: '就绪',
    bajada: 'WiWO Me · 高管智能助手',
    tituloBase: (base: string, privacidad: string) => `数据库 ${base}，隐私模式 ${privacidad}`,
    registroTecnico: '技术日志',
    vaciarConversacion: '清空对话',
    confirmarVaciado: '确定清空？',
    etiquetaOrbeApertura: 'WiWO Me Thinking Orb',
    aperturaTitulo: '向业务运营提问。',
    aperturaTexto:
      '自 2025 年 3 月起共 87,441 张服务券，包含经销商、网点、顾问和车辆信息。用自然语言提问，Thinking Orb 会查询数据库，并给出带有时间段的数字。',
    consultandoBase: '正在查询数据库：',
    pensando: '思考中',
    consultasALaBase: (cantidad: number) => `${cantidad} 次数据库查询`,
    placeholder: '向 Thinking Orb 提问…',
    etiquetaEntrada: '输入你的问题',
    detenerConsulta: '停止查询',
    enviarPregunta: '发送问题',
    aviso: 'Thinking Orb 只读取数据库。除针对性查询外，个人数据均已脱敏。',
    servidorRespondio: (estado: number) => `服务器返回 ${estado}。`,
    consultaFallida: '查询未能完成。',
    orbe: {
      reposo: 'Thinking Orb 待机中',
      escuchando: 'Thinking Orb 正在聆听',
      pensando: 'Thinking Orb 正在思考',
      generando: 'Thinking Orb 正在回答',
      error: 'Thinking Orb 出现问题',
    },
    diagnostico: {
      tipo: { ronda: '模型', herramienta: '数据库', error: '错误', turno: '轮次' },
      titulo: '技术日志',
      eventos: (cantidad: number) => `${cantidad} 个事件`,
      leyendo: '读取中…',
      recargar: '重新加载',
      vaciar: '清空',
      cerrar: '关闭',
      errorLectura: '无法读取服务器日志。',
      vacio: '暂无事件。提一个问题后再来查看。',
    },
  },
};
